-- =============================================================
-- 01_RBAC.SQL
-- Role-Based Access Control (RBAC) Setup
-- Implements principle of least privilege across all layers
-- Author: Data Engineering Team | Version: 1.0
-- =============================================================
-- Run as ACCOUNTADMIN

USE ROLE ACCOUNTADMIN;

-- ─────────────────────────────────────────────
-- FUNCTIONAL ROLES  (job-function based)
-- ─────────────────────────────────────────────

-- Data Engineer: full access to pipeline layers
CREATE ROLE IF NOT EXISTS DATA_ENGINEER_ROLE
    COMMENT = 'Data engineers — full pipeline access';

-- DBT Transformer: write staging + analytics, read raw
CREATE ROLE IF NOT EXISTS DBT_ROLE
    COMMENT = 'DBT service account — transform raw to analytics';

-- Loader: load data into raw layer only
CREATE ROLE IF NOT EXISTS LOADER_ROLE
    COMMENT = 'ETL loader — write to RAW_DB only';

-- Analyst: read analytics layer, no raw access
CREATE ROLE IF NOT EXISTS ANALYST_ROLE
    COMMENT = 'Business analysts — read analytics marts';

-- Data Steward: governance, masking, tagging
CREATE ROLE IF NOT EXISTS DATA_STEWARD_ROLE
    COMMENT = 'Data governance — manage policies and tags';

-- Read-Only Reporter: BI tools (Tableau, Looker service accounts)
CREATE ROLE IF NOT EXISTS BI_READER_ROLE
    COMMENT = 'BI tool service accounts — read-only analytics';

-- CI/CD Role: deploy DBT models in pipelines
CREATE ROLE IF NOT EXISTS CICD_ROLE
    COMMENT = 'GitHub Actions service account for CI/CD deployments';

-- ─────────────────────────────────────────────
-- ROLE HIERARCHY
-- ─────────────────────────────────────────────
GRANT ROLE LOADER_ROLE       TO ROLE DATA_ENGINEER_ROLE;
GRANT ROLE DBT_ROLE          TO ROLE DATA_ENGINEER_ROLE;
GRANT ROLE ANALYST_ROLE      TO ROLE DATA_ENGINEER_ROLE;
GRANT ROLE BI_READER_ROLE    TO ROLE ANALYST_ROLE;
GRANT ROLE DATA_ENGINEER_ROLE TO ROLE SYSADMIN;
GRANT ROLE DATA_STEWARD_ROLE TO ROLE SYSADMIN;
GRANT ROLE CICD_ROLE         TO ROLE DATA_ENGINEER_ROLE;

-- ─────────────────────────────────────────────
-- WAREHOUSE GRANTS
-- ─────────────────────────────────────────────
GRANT USAGE ON WAREHOUSE LOAD_WH       TO ROLE LOADER_ROLE;
GRANT USAGE ON WAREHOUSE LOAD_WH       TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH  TO ROLE DBT_ROLE;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH  TO ROLE ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH  TO ROLE BI_READER_ROLE;
GRANT USAGE ON WAREHOUSE ADMIN_WH      TO ROLE DATA_STEWARD_ROLE;

-- Allow roles to modify warehouse size (engineers only)
GRANT MODIFY ON WAREHOUSE TRANSFORM_WH TO ROLE DATA_ENGINEER_ROLE;

-- ─────────────────────────────────────────────
-- DATABASE GRANTS — RAW_DB
-- ─────────────────────────────────────────────
GRANT USAGE ON DATABASE RAW_DB TO ROLE LOADER_ROLE;
GRANT USAGE ON DATABASE RAW_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON DATABASE RAW_DB TO ROLE DBT_ROLE;

GRANT USAGE ON SCHEMA RAW_DB.ORACLE_RAW TO ROLE LOADER_ROLE;
GRANT USAGE ON SCHEMA RAW_DB.ORACLE_RAW TO ROLE DBT_ROLE;

-- Loader: write to RAW only
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA RAW_DB.ORACLE_RAW TO ROLE LOADER_ROLE;
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA RAW_DB.ORACLE_RAW TO ROLE LOADER_ROLE;
GRANT USAGE ON ALL STAGES IN SCHEMA RAW_DB.PUBLIC TO ROLE LOADER_ROLE;

-- DBT: read raw
GRANT SELECT ON ALL TABLES IN SCHEMA RAW_DB.ORACLE_RAW TO ROLE DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW_DB.ORACLE_RAW TO ROLE DBT_ROLE;
GRANT SELECT ON ALL STREAMS IN SCHEMA RAW_DB.ORACLE_RAW TO ROLE DBT_ROLE;

-- ─────────────────────────────────────────────
-- DATABASE GRANTS — STAGING_DB
-- ─────────────────────────────────────────────
GRANT USAGE  ON DATABASE STAGING_DB TO ROLE DBT_ROLE;
GRANT USAGE  ON SCHEMA   STAGING_DB.ORACLE_STAGE TO ROLE DBT_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE
    ON SCHEMA STAGING_DB.ORACLE_STAGE TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA STAGING_DB.ORACLE_STAGE TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA STAGING_DB.ORACLE_STAGE TO ROLE DBT_ROLE;

-- ─────────────────────────────────────────────
-- DATABASE GRANTS — ANALYTICS_DB
-- ─────────────────────────────────────────────
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE DBT_ROLE;
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE ANALYTICS_DB TO ROLE BI_READER_ROLE;

-- DBT: write analytics
GRANT USAGE, CREATE TABLE, CREATE VIEW ON ALL SCHEMAS IN DATABASE ANALYTICS_DB TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE ANALYTICS_DB TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE ANALYTICS_DB TO ROLE DBT_ROLE;

-- Analysts: read analytics
GRANT USAGE ON ALL SCHEMAS IN DATABASE ANALYTICS_DB TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS_DB TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE ANALYTICS_DB TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE ANALYTICS_DB TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE ANALYTICS_DB TO ROLE ANALYST_ROLE;

-- BI Readers: same as analysts but separate role
GRANT USAGE ON ALL SCHEMAS IN DATABASE ANALYTICS_DB TO ROLE BI_READER_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS_DB TO ROLE BI_READER_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE ANALYTICS_DB TO ROLE BI_READER_ROLE;

-- ─────────────────────────────────────────────
-- DATABASE GRANTS — AUDIT_DB
-- ─────────────────────────────────────────────
GRANT USAGE ON DATABASE AUDIT_DB TO ROLE LOADER_ROLE;
GRANT USAGE ON DATABASE AUDIT_DB TO ROLE DBT_ROLE;
GRANT USAGE ON DATABASE AUDIT_DB TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AUDIT_DB TO ROLE LOADER_ROLE;
GRANT INSERT, SELECT ON ALL TABLES IN DATABASE AUDIT_DB TO ROLE LOADER_ROLE;
GRANT INSERT, SELECT ON FUTURE TABLES IN DATABASE AUDIT_DB TO ROLE LOADER_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE AUDIT_DB TO ROLE ANALYST_ROLE;

-- ─────────────────────────────────────────────
-- SERVICE ACCOUNTS (Users)
-- ─────────────────────────────────────────────

-- Airflow service account
CREATE USER IF NOT EXISTS SVC_AIRFLOW
    LOGIN_NAME        = 'SVC_AIRFLOW'
    DISPLAY_NAME      = 'Airflow ETL Service Account'
    DEFAULT_ROLE      = LOADER_ROLE
    DEFAULT_WAREHOUSE = LOAD_WH
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT           = 'Used by Apache Airflow for data loading';

GRANT ROLE LOADER_ROLE TO USER SVC_AIRFLOW;

-- DBT service account
CREATE USER IF NOT EXISTS SVC_DBT
    LOGIN_NAME        = 'SVC_DBT'
    DISPLAY_NAME      = 'DBT Transformation Service Account'
    DEFAULT_ROLE      = DBT_ROLE
    DEFAULT_WAREHOUSE = TRANSFORM_WH
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT           = 'Used by DBT for model transformations';

GRANT ROLE DBT_ROLE TO USER SVC_DBT;

-- CI/CD service account (key-pair auth only)
CREATE USER IF NOT EXISTS SVC_CICD
    LOGIN_NAME        = 'SVC_CICD'
    DISPLAY_NAME      = 'GitHub Actions CI/CD Service Account'
    DEFAULT_ROLE      = CICD_ROLE
    DEFAULT_WAREHOUSE = TRANSFORM_WH
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT           = 'Used by GitHub Actions for automated deployments';

GRANT ROLE CICD_ROLE TO USER SVC_CICD;
GRANT ROLE DBT_ROLE  TO USER SVC_CICD;
